import Image from "next/image";
import Home from "./Home/page";
import Head from "next/head";
export default function Top() {
  return (
    <>
    <div>

    <Head>
      <title>Kaushik</title>
      <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Home/>
    </div>
    </>
  );
}
